// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: traffic_signal.proto
// Protobuf C++ Version: 6.33.4

#ifndef traffic_5fsignal_2eproto_2epb_2eh
#define traffic_5fsignal_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_traffic_5fsignal_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_traffic_5fsignal_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_traffic_5fsignal_2eproto;
}  // extern "C"
namespace traffic_signal {
enum LightColor : int;
extern const uint32_t LightColor_internal_data_[];
class TrafficLightCommand;
struct TrafficLightCommandDefaultTypeInternal;
extern TrafficLightCommandDefaultTypeInternal _TrafficLightCommand_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TrafficLightCommand_class_data_;
class TrafficLightStatus;
struct TrafficLightStatusDefaultTypeInternal;
extern TrafficLightStatusDefaultTypeInternal _TrafficLightStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TrafficLightStatus_class_data_;
}  // namespace traffic_signal
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::traffic_signal::LightColor_internal_data_>
    internal::EnumTraitsImpl::value<::traffic_signal::LightColor>;
}  // namespace protobuf
}  // namespace google

namespace traffic_signal {
enum LightColor : int {
  RED = 0,
  GREEN = 1,
  ORANGE = 2,
  DEFAULT = 3,
  LightColor_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  LightColor_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t LightColor_internal_data_[];
inline constexpr LightColor LightColor_MIN =
    static_cast<LightColor>(0);
inline constexpr LightColor LightColor_MAX =
    static_cast<LightColor>(3);
inline bool LightColor_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int LightColor_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL LightColor_descriptor();
template <typename T>
const ::std::string& LightColor_Name(T value) {
  static_assert(::std::is_same<T, LightColor>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to LightColor_Name().");
  return LightColor_Name(static_cast<LightColor>(value));
}
template <>
inline const ::std::string& LightColor_Name(LightColor value) {
  return ::google::protobuf::internal::NameOfDenseEnum<LightColor_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool LightColor_Parse(
    ::absl::string_view name, LightColor* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<LightColor>(LightColor_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class TrafficLightStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:traffic_signal.TrafficLightStatus) */ {
 public:
  inline TrafficLightStatus() : TrafficLightStatus(nullptr) {}
  ~TrafficLightStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrafficLightStatus* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrafficLightStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrafficLightStatus(::google::protobuf::internal::ConstantInitialized);

  inline TrafficLightStatus(const TrafficLightStatus& from) : TrafficLightStatus(nullptr, from) {}
  inline TrafficLightStatus(TrafficLightStatus&& from) noexcept
      : TrafficLightStatus(nullptr, ::std::move(from)) {}
  inline TrafficLightStatus& operator=(const TrafficLightStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrafficLightStatus& operator=(TrafficLightStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrafficLightStatus& default_instance() {
    return *reinterpret_cast<const TrafficLightStatus*>(
        &_TrafficLightStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TrafficLightStatus& a, TrafficLightStatus& b) { a.Swap(&b); }
  inline void Swap(TrafficLightStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrafficLightStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrafficLightStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrafficLightStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrafficLightStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrafficLightStatus& from) { TrafficLightStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrafficLightStatus* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "traffic_signal.TrafficLightStatus"; }

  explicit TrafficLightStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TrafficLightStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TrafficLightStatus& from);
  TrafficLightStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TrafficLightStatus&& from) noexcept
      : TrafficLightStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kColorFieldNumber = 2,
  };
  // string id = 1;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // .traffic_signal.LightColor color = 2;
  void clear_color() ;
  ::traffic_signal::LightColor color() const;
  void set_color(::traffic_signal::LightColor value);

  private:
  ::traffic_signal::LightColor _internal_color() const;
  void _internal_set_color(::traffic_signal::LightColor value);

  public:
  // @@protoc_insertion_point(class_scope:traffic_signal.TrafficLightStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TrafficLightStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    int color_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_traffic_5fsignal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TrafficLightStatus_class_data_;
// -------------------------------------------------------------------

class TrafficLightCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:traffic_signal.TrafficLightCommand) */ {
 public:
  inline TrafficLightCommand() : TrafficLightCommand(nullptr) {}
  ~TrafficLightCommand() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrafficLightCommand* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrafficLightCommand));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrafficLightCommand(::google::protobuf::internal::ConstantInitialized);

  inline TrafficLightCommand(const TrafficLightCommand& from) : TrafficLightCommand(nullptr, from) {}
  inline TrafficLightCommand(TrafficLightCommand&& from) noexcept
      : TrafficLightCommand(nullptr, ::std::move(from)) {}
  inline TrafficLightCommand& operator=(const TrafficLightCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrafficLightCommand& operator=(TrafficLightCommand&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrafficLightCommand& default_instance() {
    return *reinterpret_cast<const TrafficLightCommand*>(
        &_TrafficLightCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TrafficLightCommand& a, TrafficLightCommand& b) { a.Swap(&b); }
  inline void Swap(TrafficLightCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrafficLightCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrafficLightCommand* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrafficLightCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrafficLightCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrafficLightCommand& from) { TrafficLightCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrafficLightCommand* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "traffic_signal.TrafficLightCommand"; }

  explicit TrafficLightCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TrafficLightCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TrafficLightCommand& from);
  TrafficLightCommand(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TrafficLightCommand&& from) noexcept
      : TrafficLightCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kTargetColorFieldNumber = 2,
  };
  // string id = 1;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // .traffic_signal.LightColor target_color = 2;
  void clear_target_color() ;
  ::traffic_signal::LightColor target_color() const;
  void set_target_color(::traffic_signal::LightColor value);

  private:
  ::traffic_signal::LightColor _internal_target_color() const;
  void _internal_set_target_color(::traffic_signal::LightColor value);

  public:
  // @@protoc_insertion_point(class_scope:traffic_signal.TrafficLightCommand)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 45,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TrafficLightCommand& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    int target_color_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_traffic_5fsignal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TrafficLightCommand_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TrafficLightStatus

// string id = 1;
inline void TrafficLightStatus::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& TrafficLightStatus::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic_signal.TrafficLightStatus.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TrafficLightStatus::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:traffic_signal.TrafficLightStatus.id)
}
inline ::std::string* PROTOBUF_NONNULL TrafficLightStatus::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:traffic_signal.TrafficLightStatus.id)
  return _s;
}
inline const ::std::string& TrafficLightStatus::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void TrafficLightStatus::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TrafficLightStatus::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TrafficLightStatus::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:traffic_signal.TrafficLightStatus.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void TrafficLightStatus::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:traffic_signal.TrafficLightStatus.id)
}

// .traffic_signal.LightColor color = 2;
inline void TrafficLightStatus::clear_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.color_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::traffic_signal::LightColor TrafficLightStatus::color() const {
  // @@protoc_insertion_point(field_get:traffic_signal.TrafficLightStatus.color)
  return _internal_color();
}
inline void TrafficLightStatus::set_color(::traffic_signal::LightColor value) {
  _internal_set_color(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:traffic_signal.TrafficLightStatus.color)
}
inline ::traffic_signal::LightColor TrafficLightStatus::_internal_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::traffic_signal::LightColor>(_impl_.color_);
}
inline void TrafficLightStatus::_internal_set_color(::traffic_signal::LightColor value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.color_ = value;
}

// -------------------------------------------------------------------

// TrafficLightCommand

// string id = 1;
inline void TrafficLightCommand::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& TrafficLightCommand::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic_signal.TrafficLightCommand.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TrafficLightCommand::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:traffic_signal.TrafficLightCommand.id)
}
inline ::std::string* PROTOBUF_NONNULL TrafficLightCommand::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:traffic_signal.TrafficLightCommand.id)
  return _s;
}
inline const ::std::string& TrafficLightCommand::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void TrafficLightCommand::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TrafficLightCommand::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TrafficLightCommand::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:traffic_signal.TrafficLightCommand.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void TrafficLightCommand::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:traffic_signal.TrafficLightCommand.id)
}

// .traffic_signal.LightColor target_color = 2;
inline void TrafficLightCommand::clear_target_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_color_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::traffic_signal::LightColor TrafficLightCommand::target_color() const {
  // @@protoc_insertion_point(field_get:traffic_signal.TrafficLightCommand.target_color)
  return _internal_target_color();
}
inline void TrafficLightCommand::set_target_color(::traffic_signal::LightColor value) {
  _internal_set_target_color(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:traffic_signal.TrafficLightCommand.target_color)
}
inline ::traffic_signal::LightColor TrafficLightCommand::_internal_target_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::traffic_signal::LightColor>(_impl_.target_color_);
}
inline void TrafficLightCommand::_internal_set_target_color(::traffic_signal::LightColor value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_color_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace traffic_signal


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::traffic_signal::LightColor> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::traffic_signal::LightColor>() {
  return ::traffic_signal::LightColor_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // traffic_5fsignal_2eproto_2epb_2eh
