// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: traffic_signal.proto
// Protobuf C++ Version: 6.33.4

#include "traffic_signal.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace traffic_signal {

inline constexpr TrafficLightStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        color_{static_cast< ::traffic_signal::LightColor >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR TrafficLightStatus::TrafficLightStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TrafficLightStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TrafficLightStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrafficLightStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrafficLightStatusDefaultTypeInternal() {}
  union {
    TrafficLightStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrafficLightStatusDefaultTypeInternal _TrafficLightStatus_default_instance_;

inline constexpr TrafficLightCommand::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        target_color_{static_cast< ::traffic_signal::LightColor >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR TrafficLightCommand::TrafficLightCommand(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TrafficLightCommand_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TrafficLightCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrafficLightCommandDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrafficLightCommandDefaultTypeInternal() {}
  union {
    TrafficLightCommand _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrafficLightCommandDefaultTypeInternal _TrafficLightCommand_default_instance_;
}  // namespace traffic_signal
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_traffic_5fsignal_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_traffic_5fsignal_2eproto = nullptr;
const ::uint32_t
    TableStruct_traffic_5fsignal_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::traffic_signal::TrafficLightStatus, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::traffic_signal::TrafficLightStatus, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::traffic_signal::TrafficLightStatus, _impl_.color_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::traffic_signal::TrafficLightCommand, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::traffic_signal::TrafficLightCommand, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::traffic_signal::TrafficLightCommand, _impl_.target_color_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::traffic_signal::TrafficLightStatus)},
        {7, sizeof(::traffic_signal::TrafficLightCommand)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::traffic_signal::_TrafficLightStatus_default_instance_._instance,
    &::traffic_signal::_TrafficLightCommand_default_instance_._instance,
};
const char descriptor_table_protodef_traffic_5fsignal_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024traffic_signal.proto\022\016traffic_signal\"K"
    "\n\022TrafficLightStatus\022\n\n\002id\030\001 \001(\t\022)\n\005colo"
    "r\030\002 \001(\0162\032.traffic_signal.LightColor\"S\n\023T"
    "rafficLightCommand\022\n\n\002id\030\001 \001(\t\0220\n\014target"
    "_color\030\002 \001(\0162\032.traffic_signal.LightColor"
    "*9\n\nLightColor\022\007\n\003RED\020\000\022\t\n\005GREEN\020\001\022\n\n\006OR"
    "ANGE\020\002\022\013\n\007DEFAULT\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_traffic_5fsignal_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_traffic_5fsignal_2eproto = {
    false,
    false,
    267,
    descriptor_table_protodef_traffic_5fsignal_2eproto,
    "traffic_signal.proto",
    &descriptor_table_traffic_5fsignal_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_traffic_5fsignal_2eproto::offsets,
    file_level_enum_descriptors_traffic_5fsignal_2eproto,
    file_level_service_descriptors_traffic_5fsignal_2eproto,
};
namespace traffic_signal {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL LightColor_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_traffic_5fsignal_2eproto);
  return file_level_enum_descriptors_traffic_5fsignal_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t LightColor_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class TrafficLightStatus::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TrafficLightStatus>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TrafficLightStatus, _impl_._has_bits_);
};

TrafficLightStatus::TrafficLightStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TrafficLightStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:traffic_signal.TrafficLightStatus)
}
PROTOBUF_NDEBUG_INLINE TrafficLightStatus::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::traffic_signal::TrafficLightStatus& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_) {}

TrafficLightStatus::TrafficLightStatus(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TrafficLightStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TrafficLightStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TrafficLightStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.color_ = from._impl_.color_;

  // @@protoc_insertion_point(copy_constructor:traffic_signal.TrafficLightStatus)
}
PROTOBUF_NDEBUG_INLINE TrafficLightStatus::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena) {}

inline void TrafficLightStatus::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.color_ = {};
}
TrafficLightStatus::~TrafficLightStatus() {
  // @@protoc_insertion_point(destructor:traffic_signal.TrafficLightStatus)
  SharedDtor(*this);
}
inline void TrafficLightStatus::SharedDtor(MessageLite& self) {
  TrafficLightStatus& this_ = static_cast<TrafficLightStatus&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TrafficLightStatus::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TrafficLightStatus(arena);
}
constexpr auto TrafficLightStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TrafficLightStatus),
                                            alignof(TrafficLightStatus));
}
constexpr auto TrafficLightStatus::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TrafficLightStatus_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TrafficLightStatus::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TrafficLightStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TrafficLightStatus::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TrafficLightStatus>(), &TrafficLightStatus::ByteSizeLong,
              &TrafficLightStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TrafficLightStatus, _impl_._cached_size_),
          false,
      },
      &TrafficLightStatus::kDescriptorMethods,
      &descriptor_table_traffic_5fsignal_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TrafficLightStatus_class_data_ =
        TrafficLightStatus::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TrafficLightStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TrafficLightStatus_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TrafficLightStatus_class_data_.tc_table);
  return TrafficLightStatus_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2>
TrafficLightStatus::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TrafficLightStatus, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TrafficLightStatus_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::traffic_signal::TrafficLightStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .traffic_signal.LightColor color = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TrafficLightStatus, _impl_.color_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(TrafficLightStatus, _impl_.color_)}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(TrafficLightStatus, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(TrafficLightStatus, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .traffic_signal.LightColor color = 2;
    {PROTOBUF_FIELD_OFFSET(TrafficLightStatus, _impl_.color_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\41\2\0\0\0\0\0\0"
    "traffic_signal.TrafficLightStatus"
    "id"
  }},
};
PROTOBUF_NOINLINE void TrafficLightStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:traffic_signal.TrafficLightStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.id_.ClearNonDefaultToEmpty();
  }
  _impl_.color_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TrafficLightStatus::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TrafficLightStatus& this_ = static_cast<const TrafficLightStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TrafficLightStatus::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TrafficLightStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:traffic_signal.TrafficLightStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_id().empty()) {
      const ::std::string& _s = this_._internal_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "traffic_signal.TrafficLightStatus.id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .traffic_signal.LightColor color = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_color() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_color(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:traffic_signal.TrafficLightStatus)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TrafficLightStatus::ByteSizeLong(const MessageLite& base) {
  const TrafficLightStatus& this_ = static_cast<const TrafficLightStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TrafficLightStatus::ByteSizeLong() const {
  const TrafficLightStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:traffic_signal.TrafficLightStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_id());
      }
    }
    // .traffic_signal.LightColor color = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_color() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_color());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TrafficLightStatus::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TrafficLightStatus*>(&to_msg);
  auto& from = static_cast<const TrafficLightStatus&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:traffic_signal.TrafficLightStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_id().empty()) {
        _this->_internal_set_id(from._internal_id());
      } else {
        if (_this->_impl_.id_.IsDefault()) {
          _this->_internal_set_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_color() != 0) {
        _this->_impl_.color_ = from._impl_.color_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TrafficLightStatus::CopyFrom(const TrafficLightStatus& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:traffic_signal.TrafficLightStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TrafficLightStatus::InternalSwap(TrafficLightStatus* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  swap(_impl_.color_, other->_impl_.color_);
}

::google::protobuf::Metadata TrafficLightStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TrafficLightCommand::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TrafficLightCommand>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TrafficLightCommand, _impl_._has_bits_);
};

TrafficLightCommand::TrafficLightCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TrafficLightCommand_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:traffic_signal.TrafficLightCommand)
}
PROTOBUF_NDEBUG_INLINE TrafficLightCommand::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::traffic_signal::TrafficLightCommand& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_) {}

TrafficLightCommand::TrafficLightCommand(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TrafficLightCommand& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TrafficLightCommand_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TrafficLightCommand* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.target_color_ = from._impl_.target_color_;

  // @@protoc_insertion_point(copy_constructor:traffic_signal.TrafficLightCommand)
}
PROTOBUF_NDEBUG_INLINE TrafficLightCommand::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena) {}

inline void TrafficLightCommand::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.target_color_ = {};
}
TrafficLightCommand::~TrafficLightCommand() {
  // @@protoc_insertion_point(destructor:traffic_signal.TrafficLightCommand)
  SharedDtor(*this);
}
inline void TrafficLightCommand::SharedDtor(MessageLite& self) {
  TrafficLightCommand& this_ = static_cast<TrafficLightCommand&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TrafficLightCommand::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TrafficLightCommand(arena);
}
constexpr auto TrafficLightCommand::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TrafficLightCommand),
                                            alignof(TrafficLightCommand));
}
constexpr auto TrafficLightCommand::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TrafficLightCommand_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TrafficLightCommand::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TrafficLightCommand>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TrafficLightCommand::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TrafficLightCommand>(), &TrafficLightCommand::ByteSizeLong,
              &TrafficLightCommand::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TrafficLightCommand, _impl_._cached_size_),
          false,
      },
      &TrafficLightCommand::kDescriptorMethods,
      &descriptor_table_traffic_5fsignal_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TrafficLightCommand_class_data_ =
        TrafficLightCommand::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TrafficLightCommand::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TrafficLightCommand_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TrafficLightCommand_class_data_.tc_table);
  return TrafficLightCommand_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 45, 2>
TrafficLightCommand::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TrafficLightCommand, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TrafficLightCommand_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::traffic_signal::TrafficLightCommand>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .traffic_signal.LightColor target_color = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TrafficLightCommand, _impl_.target_color_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(TrafficLightCommand, _impl_.target_color_)}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(TrafficLightCommand, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(TrafficLightCommand, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .traffic_signal.LightColor target_color = 2;
    {PROTOBUF_FIELD_OFFSET(TrafficLightCommand, _impl_.target_color_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\42\2\0\0\0\0\0\0"
    "traffic_signal.TrafficLightCommand"
    "id"
  }},
};
PROTOBUF_NOINLINE void TrafficLightCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:traffic_signal.TrafficLightCommand)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.id_.ClearNonDefaultToEmpty();
  }
  _impl_.target_color_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TrafficLightCommand::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TrafficLightCommand& this_ = static_cast<const TrafficLightCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TrafficLightCommand::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TrafficLightCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:traffic_signal.TrafficLightCommand)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_id().empty()) {
      const ::std::string& _s = this_._internal_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "traffic_signal.TrafficLightCommand.id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .traffic_signal.LightColor target_color = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_target_color() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_target_color(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:traffic_signal.TrafficLightCommand)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TrafficLightCommand::ByteSizeLong(const MessageLite& base) {
  const TrafficLightCommand& this_ = static_cast<const TrafficLightCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TrafficLightCommand::ByteSizeLong() const {
  const TrafficLightCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:traffic_signal.TrafficLightCommand)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_id());
      }
    }
    // .traffic_signal.LightColor target_color = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_target_color() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_target_color());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TrafficLightCommand::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TrafficLightCommand*>(&to_msg);
  auto& from = static_cast<const TrafficLightCommand&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:traffic_signal.TrafficLightCommand)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_id().empty()) {
        _this->_internal_set_id(from._internal_id());
      } else {
        if (_this->_impl_.id_.IsDefault()) {
          _this->_internal_set_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_target_color() != 0) {
        _this->_impl_.target_color_ = from._impl_.target_color_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TrafficLightCommand::CopyFrom(const TrafficLightCommand& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:traffic_signal.TrafficLightCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TrafficLightCommand::InternalSwap(TrafficLightCommand* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  swap(_impl_.target_color_, other->_impl_.target_color_);
}

::google::protobuf::Metadata TrafficLightCommand::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace traffic_signal
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_traffic_5fsignal_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
