#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "message.pb.h" // The file generated by protoc

void MainWindow::on_saveBtn_clicked() {
    // 1. Fill the Protobuf object
    Person person;
    person.set_name(ui->nameEdit->text().toStdString());
    person.set_id(123);

    // 2. Serialize (example: to standard string)
    std::string serializedData = person.SerializeAsString();

    // 3. UI Feedback
    ui->statusLabel->setText(QString("Serialized: %1").arg(person.name().c_str()));
}

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
}

MainWindow::~MainWindow()
{
    delete ui;
}
